engines:
  eslint:
    enabled: false
  pep8:
    enabled: true
  fixme:
    enabled: true
  radon:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
      - python:
ratings:
   paths:
   - "souschef/**/*.py"
   # - souschef/**/*.js
exclude_paths:
- "**/tests.py"
- "docs/**/*"
- "*.csv"
