version: '3'
services:

  db:
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: feast

  web:
    command: python src/manage.py runserver 0.0.0.0:8000
    environment:
      - SOUSCHEF_ENVIRONMENT_NAME=DEV
      - SOUSCHEF_DJANGO_ALLOWED_HOSTS=0.0.0.0 127.0.0.1 localhost
    volumes:
      - .:/code
    ports:
      - "8000:8000"
