version: '3'

services:

  db:
    restart: always
    image: mariadb
    volumes:
      - souschef_data:/var/lib/mysql
    networks:
      - backend

  web:
    restart: always
    build: .
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend

volumes:
  souschef_data:

networks:
  backend:
