name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Flake8 with annotations
      uses: TrueBrain/actions-flake8@v1.2
      with:
       path: src
